### ISSUE TITLE
Custom Settings Component

### ISSUE THREAD

**Issue by ryanlanciaux** [GriddleGriddle/griddle-render#17]
Settings should be overridable so people can define their own and not be tied to Griddle's defaults.

See https://github.com/GriddleGriddle/Griddle/issues/84

**Comment by moimikey** [comment]
yaaaassssssss! +1

**Comment by ryanlanciaux** [comment]
This is working and will be part of the Griddle 1.0 alpha.

**Comment by jesseproudman** [comment]
Did this ever get bundled in? I don't see a way to do:

 customFilterComponent: PropertyTableFilter
useCustomSettingsComponent: true

Thanks!
