### ISSUE TITLE
Remove unnecessary modules

### ISSUE THREAD

**Issue by ryanlanciaux** [GriddleGriddle/griddle-render#28]
There are some files that are still being installed with griddle-render that are unnecessary.

**Comment by yorchv** [comment]
I can help you with this. Is this still required?

**Comment by ryanlanciaux** [comment]
That would be awesome. I think it's mostly jsx-loader (since babel should handle this now) https://github.com/GriddleGriddle/griddle-render/blob/master/package.json#L23

And ReactDraggable since we are trying to push non-core functionality to plugins (meaning I think there should be a plugin for adding drag-to-resize columns).

Griddle core also suffers from this a bit (here's [the project's package.json](https://github.com/GriddleGriddle/griddle-core/blob/master/package.json)) -- initially we were building everything as one module and more recently split it up and there are artifacts of that still that we need to get cleaned up before the release is actually ready. If you wanted to take on one that is more than just a couple modules :) That one should be a bit nicer to make sure everything's okay too since we have tests around most of that side Core shouldn't have any of the react rendering logic since it's the module that is used solely for state management

**Comment by yorchv** [comment]
You got it
https://github.com/GriddleGriddle/griddle-render/pull/40

**Comment by ryanlanciaux** [comment]
@yorchv Took care of this one :) Thanks again :tada:
