### ISSUE TITLE
move react to peerDeps

### ISSUE THREAD

**Issue by Guria** [GriddleGriddle/griddle-render#46]
Defining `react` as regular dep in library could lead to several react instances on project. Which will lead to hard debugging.

**Comment by Guria** [comment]
![](http://i.imgur.com/YRZhg4m.png)

should be fixed in other packages as well

**Comment by ryanlanciaux** [comment]
Thanks for catching this also! We'll switch that around because as you said that's a big pain to debug

**Comment by ryanlanciaux** [comment]
Thanks this has been updated!

**Comment by PsycheSloLo811** [comment]
`4.0

`
